version: "3.9"
services:
  rm:
    build: 
      context: ./rm
    ports:
      - "5000:3000"
    volumes:
      - ./rm:/rm
    depends_on:
      - db
    deploy:
      restart_policy:
        max_attempts: 3
        condition: on-failure
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 5E^&()VB78954!@PG
      POSTGRES_USER: rms
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    ports:
      - "15432:5432"
    volumes:
      - rms-db:/data/db
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: uppist
      MONGO_INITDB_ROOT_PASSWORD: k0WmKa49SG8TUNSc
    volumes:
      - pos-db:/data/db
  
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGO_AUTH_USERNAME: uppist
      ME_CONFIG_MONGO_AUTH_PASSWORD: k0WmKa49SG8TUNSc
      ME_CONFIG_MONGO_URL: mongodb+srv://uppist:k0WmKa49SG8TUNSc@pos-server.4frvfqt.mongodb.net/?retryWrites=true&w=majority

    depends_on:
      - mongo

volumes:
  rms-db:
    name: "rms-app-db"
  pos-db:
    name: "pos-mongo-db"
