version: "3.9"
services:
  rm:
    build: .
    ports:
      - "5000:3000"
    volumes:
      - ./:/rms
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 5E^&()VB78954!@PG
      POSTGRES_USER: rms
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    ports:
      - "15432:5432"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - rms-db:/usr/docker/volumes
volumes:
  rms-db:
    name: "rms-app-db"
